---
### Logging config (default is stdout, or provide path to log file)
# log: stdout
# log: /var/log/poni.log

### optional Global sync settings
defaults:
  source_path: /opt/dir1
  remote_host: nycweb1
  remote_path: /tmp
  remote_user: bob
  priv_key: /home/bob/.ssh/id_rsa
  rsync_opts: azP
  interval: 3
  recurse: false
  port: 22

## Remote syncs (can specify sync settings for each file or folder)
sync:
  ## these syncs use specific sync values
  "sync dir3 to nycweb1:/opt": # unique name for each sync
    source_path: /opt/dir3
    remote_host: nycweb1
    remote_path: /opt
    remote_user: jsmith
    priv_key: /home/jsmith/.ssh/id_rsa
    rsync_opts: azBP
    interval: 15
    recurse: true

  ################################################################################
  ## this sync will use Default values from "defaults" section above
  ## will sync source_host:source_path > remote_host:remote_path, using all default settings
  ## ie, localhost:/opt/dir1 > nycweb1:/tmp
  "sync default path to nycweb1:/tmp": []

  ################################################################################
  ## sync only files inside /home/joe/test, not entire "test" directory, place "/" at end of source path
  ## ie, if theres are 2 files in /home/joe/test (/home/joe/test/file1, file2) only these 2 files will be syncted to webhost2:/tmp, not entire "test" directory
  "sync only files in /home/joe/test not entire test dir":
    source_path: /home/joe/test/
    remote_host: webhost2
    remote_path: /tmp/
    remote_user: joe
    priv_key: /home/joe/.ssh/id_ed25519
    ## all other options like recurse, interval etc, will come from Defaults

  ################################################################################
  ### sync same directory or file to multiple destinations
  ### will rsync config.json to both Joe and Linda's macs as well to default target "nycweb1"
  "sync to Joe":
    source_path: /var/shared/config.json
    remote_host: joes-mac
    remote_path: /Users/joe/configs/
    remote_user: joe
    priv_key: /root/.ssh/id_ed25519 # Here, the source host's root user's pub key is in remote host's Joe's authorized_keys file
    recurse: true
    rsync opts: zvjP

  "sync to Linda":
    source_path: /var/shared/config.json
    remote_host: lindas-mac
    remote_path: /Users/linda/configs/
    remote_user: linda
    priv_key: /home/linda/.ssh/id_ed25519 # Here, the source host's Linda pub key is in remote host's (Mac) Linda's authorized_keys file
    ## all other settings will come from Defaults, ie "recurse" will be set to default "false"

  "sync to Default target": # here we will sync source path of /var/shared/config.json to default target of nycweb1 (see Default section above)
    source_path: /var/shared/config.json

