---
### Logging config (default is stdout, or provide path to log file)
# log: stdout
# log: /var/log/poni.log

### optional Global sync settings
defaults:
  remote_host: nycweb1
  remote_path: /tmp
  remote_user: bob
  priv_key: /home/bob/.ssh/id_rsa
  rsync_opts: azP
  interval: 3
  recurse: false
  port: 22


## Remote syncs (can specify sync settings for each file or folder)
sync:
  ### these 2 syncs will use default Global sync values (will sync to bob@nycweb1:/tmp)
  /opt/dir1: []
  /opt/dir2: []

  ### these syncs use specific sync values
  /opt/dir3:
    remote_host: nycweb1
    remote_path: /opt
    remote_user: jsmith
    priv_key: /home/jsmith/.ssh/id_rsa
    rsync_opts: azBP
    interval: 15
    recurse: true

  /home/joe/test:
    remote_host: localhost
    remote_path: /tmp/
    remote_user: joe
    priv_key: /home/joe/.ssh/id_ed25519
    rsync_opts: azvPj